/**
 * protocols/ArchiveFormat.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): bc7ac2330f3445983614e25bb8b518c5de89b15d05c72e1b9277ddc6c025d621
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_PROTOCOLS_ARCHIVEFORMAT_H
#define UNIARCHIVE2_PROTOCOLS_ARCHIVEFORMAT_H

#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace protocols {

enum class ArchiveFormat {
    INVALID = 0,
    ADIUM,
    DIGSBY,
    FACEBOOK_DYI,
    MSN_MESSENGER_XML,
    PIDGIN_HTML,
    PIDGIN_TXT,
    SKYPE,
    WHATSAPP_EMAIL,
    YAHOO_MESSENGER_DAT,
};

QString name_for_archive_format(ArchiveFormat format);

QDebug operator<< (QDebug stream, ArchiveFormat format);

}}

#endif //UNIARCHIVE2_PROTOCOLS_ARCHIVEFORMAT_H
