/**
 * protocols/ArchiveFormat.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): d214f5ca86c7b06f7bef0ff452268307896db24fa2fb8ad505b6780f24f548da
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "protocols/ArchiveFormat.h"
#include "utils/qt/shortcuts.h"

#include <QtDebug>

namespace uniarchive2 { namespace protocols {

QString name_for_archive_format(ArchiveFormat format) {
    switch (format) {
        case ArchiveFormat::INVALID:
            return "(invalid)";
        case ArchiveFormat::ADIUM:
            return "Adium";
        case ArchiveFormat::DIGSBY:
            return "Digsby";
        case ArchiveFormat::FACEBOOK_DYI:
            return "Facebook (DYI archive)";
        case ArchiveFormat::MSN_MESSENGER_XML:
            return "MSN Messenger (XML format)";
        case ArchiveFormat::PIDGIN_HTML:
            return "Pidgin (HTML format)";
        case ArchiveFormat::PIDGIN_TXT:
            return "Pidgin (TXT format)";
        case ArchiveFormat::SKYPE:
            return "Skype";
        case ArchiveFormat::WHATSAPP_EMAIL:
            return "WhatsApp (Email format)";
        case ArchiveFormat::YAHOO_MESSENGER_DAT:
            return "Yahoo Messenger (DAT format)";
    }

    invariant_violation("Invalid ArchiveFormat value (%lld)", (int64_t)format);
}

QDebug operator<< (QDebug stream, ArchiveFormat format) {
    stream << QP(name_for_archive_format(format));

    return stream;
}

QDataStream& operator<< (QDataStream& mut_stream, ArchiveFormat format) {
    mut_stream << (uint8_t)format;

    return mut_stream;
}

}}
