/**
 * protocols/IMProtocol.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 02f24f3a018ec27ec66352a6fe83c6edeb2838a11d0be073c8a6f88cc4d80a1d
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_PROTOCOLS_IMPROTOCOL_H
#define UNIARCHIVE2_PROTOCOLS_IMPROTOCOL_H

#include <QDebug>

namespace uniarchive2 { namespace protocols {

enum class IMProtocol {
    INVALID = 0,
    DIGSBY,
    FACEBOOK,
    JABBER,
    MSN,
    SKYPE,
    WHATSAPP,
    YAHOO,
};

QString name_for_im_protocol(IMProtocol protocol);

QDebug operator<< (QDebug stream, IMProtocol protocol);

}}

#endif //UNIARCHIVE2_PROTOCOLS_IMPROTOCOL_H
