/**
 * protocols/IMProtocol.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): d0e90b8fd81a29e2f5cc4fa71fa7e022a32bc33c2a5f620ec323b783689e1dfe
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_PROTOCOLS_IMPROTOCOL_H
#define UNIARCHIVE2_PROTOCOLS_IMPROTOCOL_H

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace protocols {

enum class IMProtocol : uint8_t {
    INVALID = 0,
    DIGSBY,
    FACEBOOK,
    JABBER,
    MSN,
    SKYPE,
    WHATSAPP,
    YAHOO,
};

QString name_for_im_protocol(IMProtocol protocol);

QDebug operator<< (QDebug stream, IMProtocol protocol);
QDataStream& operator<< (QDataStream& mut_stream, IMProtocol protocol);

}}

#endif //UNIARCHIVE2_PROTOCOLS_IMPROTOCOL_H
