/**
 * protocols/IMStatus.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 898b33aea5ee60f69585e63a66cac8ce9232f0033fb2be71d6573d7eab485832
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_PROTOCOLS_IMSTATUS_H
#define UNIARCHIVE2_PROTOCOLS_IMSTATUS_H

#include "utils/language/shortcuts.h"

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace protocols {

enum class IMStatus : uint8_t {
    INVALID = 0,
    AVAILABLE,
    AWAY,
    IDLE,
    OFFLINE,
};

QString name_for_im_status(IMStatus status);

QString symbol_for_im_status(IMStatus status);
IMStatus im_status_from_symbol(IMM(QString) symbol);

QDebug operator<< (QDebug stream, IMStatus status);

QDataStream& operator>> (QDataStream& mut_stream, IMStatus& mut_status);
QDataStream& operator<< (QDataStream& mut_stream, IMStatus status);

}}

#endif //UNIARCHIVE2_PROTOCOLS_IMSTATUS_H
