/**
 * intermediate_format/events/status/RawConnectedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 9ebbf8b80508c9ba5a769fb3ebede1e0efaca9439cd98c4087d4dacbc9c202a0
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/status/RawConnectedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawConnectedEvent::RawConnectedEvent(IMM(ApparentTime) timestamp, uint index, TAKE(ApparentSubject) subject)
  : RawEvent(timestamp, index), subject(move(subject)) {
    sanityCheckMandatoryParameters();
}

void RawConnectedEvent::sanityCheckMandatoryParameters() const {
    invariant(subject, "Parameter 'subject' cannot have empty value");
}

RawEventSubType RawConnectedEvent::subType() const {
    return RawEventSubType::CONNECTED;
}

QString RawConnectedEvent::eventName() const {
    return "Connected";
}

void RawConnectedEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " subject=" << subject.get();
}

}}}
