/**
 * intermediate_format/events/status/RawDisconnectedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 86ce197d6d7fb6dce5ef21eb9a44673eba94fa2e1d9ade61cc74ac3b5b28e5c2
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/status/RawDisconnectedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawDisconnectedEvent::RawDisconnectedEvent(IMM(ApparentTime) timestamp, uint index, TAKE(ApparentSubject) subject)
  : RawEvent(timestamp, index), subject(move(subject)) {
    sanityCheckMandatoryParameters();
}

void RawDisconnectedEvent::sanityCheckMandatoryParameters() const {
    invariant(subject, "Parameter 'subject' cannot have empty value");
}

RawEventSubType RawDisconnectedEvent::subType() const {
    return RawEventSubType::DISCONNECTED;
}

QString RawDisconnectedEvent::eventName() const {
    return "Disconnected";
}

void RawDisconnectedEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " subject=" << subject.get();
}

}}}
