/**
 * intermediate_format/events/calls/RawEndCallEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 4252147be49165d79fa153f57ba068ca1778418282c49df0afd1854477aac675
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/calls/RawEndCallEvent.h"
#include "utils/qt/debug_extras.h"
#include "utils/serialization/deserialization_helpers.h"
#include "utils/serialization/serialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::utils::serialization;

RawEndCallEvent::RawEndCallEvent(IMM(ApparentTime) timestamp, uint32_t index) : RawEvent(timestamp, index) {
}

RawEventSubType RawEndCallEvent::subType() const {
    return RawEventSubType::END_CALL;
}

CEDE(RawEndCallEvent) RawEndCallEvent::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    invariant_violation("RawEndCallEvent deserialization not yet implemented");
}

void RawEndCallEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    serialize_optional_unique_ptr(mut_stream, ender);
    mut_stream << reasonCallFailed << skypeCallGUID << syntheticCallGUID << correspondingSkypeCallID;
}

void RawEndCallEvent::writeDetailsToDebugStream(QDebug stream) const {
    if (ender) {
        stream << " ender=" << ender;
    }
    if (reasonCallFailed) {
        stream << " reason_call_failed=" << reasonCallFailed;
    }
    if (skypeCallGUID) {
        stream << " skype_call_guid=" << skypeCallGUID;
    }
    if (syntheticCallGUID) {
        stream << " synthetic_call_guid=" << syntheticCallGUID;
    }
    if (correspondingSkypeCallID) {
        stream << " corresponding_skype_call_id=" << correspondingSkypeCallID;
    }
}

}}}
