/**
 * intermediate_format/events/calls/RawOfferCallEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 422ff0f66ba0de3eae88d7e7e17f5ce1ce0cd39ce1612c99d8c27aebe6ef919f
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/calls/RawOfferCallEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawOfferCallEvent::RawOfferCallEvent(IMM(ApparentTime) timestamp, uint index, TAKE(ApparentSubject) caller)
  : RawEvent(timestamp, index), caller(move(caller)) {
    sanityCheckMandatoryParameters();
}

void RawOfferCallEvent::sanityCheckMandatoryParameters() const {
    invariant(caller, "Parameter 'caller' cannot have empty value");
}

QString RawOfferCallEvent::eventName() const {
    return "OfferCall";
}

void RawOfferCallEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " caller=" << caller.get();
}

}}}
