/**
 * intermediate_format/events/calls/RawStartCallEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 571675336af4fe8aabb949e74e3536952425e35790b4b478fa5b7ae38db81deb
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/calls/RawStartCallEvent.h"
#include "utils/qt/debug_extras.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawStartCallEvent::RawStartCallEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) initiator,
    TAKE_VEC(ApparentSubject) peers
) : RawFailableEvent(timestamp, index), initiator(move(initiator)), peers(move(peers)) {
    sanityCheckMandatoryParameters();
}

RawStartCallEvent::RawStartCallEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) initiator,
    TAKE(ApparentSubject) peer
) : RawFailableEvent(timestamp, index), initiator(move(initiator)) {
    peers.push_back(move(peer));
    sanityCheckMandatoryParameters();
}

void RawStartCallEvent::sanityCheckMandatoryParameters() const {
    invariant(initiator, "Parameter 'initiator' cannot have empty value");
    for (IMM(auto) item : peers) {
        invariant(item, "Parameter 'peers' cannot have empty entries");
    }
}

QString RawStartCallEvent::eventName() const {
    return "StartCall";
}

void RawStartCallEvent::writeFailableEventDetailsToDebugStream(QDebug stream) const {
    stream << " initiator=" << initiator.get();
    if (peers.size() == 1) {
        stream << " peer=" << peers.front();
    } else {
        stream << " peers=" << peers;
    }
    if (durationSeconds) {
        stream << " duration_seconds=" << *durationSeconds;
    }
    if (skypeCallGUID) {
        stream << " skype_call_guid=" << *skypeCallGUID;
    }
    if (syntheticCallGUID) {
        stream << " synthetic_call_guid=" << *syntheticCallGUID;
    }
    if (correspondingSkypeCallID) {
        stream << " corresponding_skype_call_id=" << *correspondingSkypeCallID;
    }
}

}}}
