/**
 * intermediate_format/events/conference/RawCreateConferenceEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 593f561f01912209853d71bf3440e5fa22d35ca69d102e3e7860a74d5608965a
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conference/RawCreateConferenceEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawCreateConferenceEvent::RawCreateConferenceEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) creator
) : RawEvent(timestamp, index), creator(move(creator)) {
}

RawCreateConferenceEvent::RawCreateConferenceEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) creator,
    IMM(QString) conference_name
) : RawEvent(timestamp, index), creator(move(creator)), conferenceName(conference_name) {
}

QString RawCreateConferenceEvent::eventName() const {
    return "CreateConference";
}

void RawCreateConferenceEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " creator=" << creator.get();
    if (conferenceName) {
        stream << " conference_name=" << *conferenceName;
    }
}

}}}
