/**
 * intermediate_format/events/conference/RawChangeTopicEvent.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 45d07c7d515662f84a617360af418cf75c696f0cf1b116c36937d76c85e7e9a1
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWCHANGETOPICEVENT_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWCHANGETOPICEVENT_H

#include "intermediate_format/content/RawMessageContent.h"
#include "intermediate_format/events/RawEvent.h"
#include "intermediate_format/subjects/ApparentSubject.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::intermediate_format::content;
using namespace uniarchive2::intermediate_format::subjects;

struct RawChangeTopicEvent : RawEvent {
public:
    unique_ptr<ApparentSubject> subject;
    RawMessageContent topic;

    RawChangeTopicEvent(
        IMM(ApparentTime) timestamp,
        uint index,
        TAKE(ApparentSubject) subject,
        RawMessageContent&& topic
    );

    virtual QString eventName() const;

protected:
    virtual void writeDetailsToDebugStream(QDebug stream) const;
};

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWCHANGETOPICEVENT_H
