/**
 * intermediate_format/events/conference/RawChangeTopicEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): a3e106ccefc68fb6b48b0033ed50222ade09c4e28440bf53c01be013be26d9ab
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conference/RawChangeTopicEvent.h"
#include "utils/qt/debug_extras.h"
#include "utils/serialization/deserialization_helpers.h"
#include "utils/serialization/serialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::utils::serialization;

RawChangeTopicEvent::RawChangeTopicEvent(
    IMM(ApparentTime) timestamp,
    uint32_t index,
    TAKE(ApparentSubject) subject,
    RawMessageContent&& topic
) : RawEvent(timestamp, index), subject(move(subject)), topic(move(topic)) {
    sanityCheckMandatoryParameters();
}

void RawChangeTopicEvent::sanityCheckMandatoryParameters() const {
    invariant(subject, "Parameter 'subject' cannot have empty value");
}

RawEventSubType RawChangeTopicEvent::subType() const {
    return RawEventSubType::CHANGE_TOPIC;
}

void RawChangeTopicEvent::visitSubjectsImpl(ApparentSubjectVisitor& UNUSED visitor) {
    // No fields to visit
}

CEDE(RawChangeTopicEvent) RawChangeTopicEvent::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    maybeDeserializeType(skip_type, mut_stream, RawEventSubType::CHANGE_TOPIC);

    ApparentTime timestamp = must_deserialize(mut_stream, ApparentTime);
    uint32_t index = must_deserialize(mut_stream, uint32_t);
    optional<QByteArray> skype_guid = must_deserialize(mut_stream, optional<QByteArray>);
    unique_ptr<ApparentSubject> subject = must_deserialize(mut_stream, unique_ptr<ApparentSubject>);
    RawMessageContent topic = must_deserialize(mut_stream, RawMessageContent);

    unique_ptr<RawChangeTopicEvent> event = make_unique<RawChangeTopicEvent>(
        timestamp,
        index,
        move(subject),
        move(topic)
    );
    event->skypeGUID = skype_guid;

    return event;
}

void RawChangeTopicEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    mut_stream << subject << topic;
}

void RawChangeTopicEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " subject=" << subject << " topic=" << topic;
}

}}}
