/**
 * intermediate_format/events/conference/RawChangeTopicEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): bcea8cc0c11ed607fa693e80931d69749fa62cfdcf94682ce857374077e00db8
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conference/RawChangeTopicEvent.h"
#include "utils/qt/debug_extras.h"
#include "utils/serialization/serialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawChangeTopicEvent::RawChangeTopicEvent(
    IMM(ApparentTime) timestamp,
    uint32_t index,
    TAKE(ApparentSubject) subject,
    RawMessageContent&& topic
) : RawEvent(timestamp, index), subject(move(subject)), topic(move(topic)) {
    sanityCheckMandatoryParameters();
}

void RawChangeTopicEvent::sanityCheckMandatoryParameters() const {
    invariant(subject, "Parameter 'subject' cannot have empty value");
}

RawEventSubType RawChangeTopicEvent::subType() const {
    return RawEventSubType::CHANGE_TOPIC;
}

void RawChangeTopicEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    mut_stream << subject << topic;
}

void RawChangeTopicEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " subject=" << subject << " topic=" << topic;
}

}}}
