/**
 * intermediate_format/events/conference/RawLeaveConferenceEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 651441aea40d7c1fa2a7b1abc3252a09377ce27730781ba0dba75359d45af438
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conference/RawLeaveConferenceEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawLeaveConferenceEvent::RawLeaveConferenceEvent(IMM(ApparentTime) timestamp, uint index, TAKE(ApparentSubject) subject)
  : RawEvent(timestamp, index), subject(move(subject)) {
    sanityCheckMandatoryParameters();
}

void RawLeaveConferenceEvent::sanityCheckMandatoryParameters() const {
    invariant(subject, "Parameter 'subject' cannot have empty value");
}

QString RawLeaveConferenceEvent::eventName() const {
    return "LeaveConference";
}

void RawLeaveConferenceEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " subject=" << subject.get();
    if (message) {
        stream << " message=" << *message;
    }
}

}}}
