/**
 * intermediate_format/events/conference/RawRejoinConferenceEvent.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 1a7673bbd65150fba943735c2b4eb2213bf23ff329f14ec726220b7dc464990b
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWREJOINCONFERENCEEVENT_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWREJOINCONFERENCEEVENT_H

#include "intermediate_format/events/RawEvent.h"
#include "intermediate_format/subjects/ApparentSubject.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::intermediate_format::subjects;

struct RawRejoinConferenceEvent : RawEvent {
public:
    unique_ptr<ApparentSubject> subject;
    vector<unique_ptr<ApparentSubject>> peers;

    RawRejoinConferenceEvent(
        IMM(ApparentTime) timestamp,
        uint index,
        TAKE(ApparentSubject) subject,
        TAKE_VEC(ApparentSubject) peers
    );

    virtual RawEventSubType subType() const;

protected:
    virtual void writeDetailsToDebugStream(QDebug stream) const;

private:
    void sanityCheckMandatoryParameters() const;
};

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWREJOINCONFERENCEEVENT_H
