/**
 * intermediate_format/events/conference/RawRemoveFromConferenceEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): fd5e017e0a98ccdbe192ffc4fbc18aeb157f3eeb4a68115e187817b71928bfcd
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conference/RawRemoveFromConferenceEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawRemoveFromConferenceEvent::RawRemoveFromConferenceEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) removee
) : RawEvent(timestamp, index), removee(move(removee)) {
    sanityCheckMandatoryParameters();
}

RawRemoveFromConferenceEvent::RawRemoveFromConferenceEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) remover,
    TAKE(ApparentSubject) removee
) : RawEvent(timestamp, index), remover(move(remover)), removee(move(removee)) {
    sanityCheckMandatoryParameters();
}

void RawRemoveFromConferenceEvent::sanityCheckMandatoryParameters() const {
    invariant(removee, "Parameter 'removee' cannot have empty value");
}

QString RawRemoveFromConferenceEvent::eventName() const {
    return "RemoveFromConference";
}

void RawRemoveFromConferenceEvent::writeDetailsToDebugStream(QDebug stream) const {
    if (remover) {
        stream << " remover=" << remover.get();
    }
    stream << " removee=" << removee.get();
}

}}}
