/**
 * intermediate_format/events/conference/RawRemoveFromConferenceEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): e2f80bccf8a87a5e9dd3edf2bb359a59c2653f513924764d99e74f19f3131a2e
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conference/RawRemoveFromConferenceEvent.h"
#include "utils/qt/debug_extras.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawRemoveFromConferenceEvent::RawRemoveFromConferenceEvent(
    IMM(ApparentTime) timestamp,
    uint32_t index,
    TAKE(ApparentSubject) removee
) : RawEvent(timestamp, index), removee(move(removee)) {
    sanityCheckMandatoryParameters();
}

RawRemoveFromConferenceEvent::RawRemoveFromConferenceEvent(
    IMM(ApparentTime) timestamp,
    uint32_t index,
    TAKE(ApparentSubject) remover,
    TAKE(ApparentSubject) removee
) : RawEvent(timestamp, index), remover(move(remover)), removee(move(removee)) {
    sanityCheckMandatoryParameters();
    invariant(this->remover, "Parameter 'remover' cannot have empty value");
}

void RawRemoveFromConferenceEvent::sanityCheckMandatoryParameters() const {
    invariant(removee, "Parameter 'removee' cannot have empty value");
}

RawEventSubType RawRemoveFromConferenceEvent::subType() const {
    return RawEventSubType::REMOVE_FROM_CONFERENCE;
}

void RawRemoveFromConferenceEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    // TODO: add field serialization code
}

void RawRemoveFromConferenceEvent::writeDetailsToDebugStream(QDebug stream) const {
    if (remover) {
        stream << " remover=" << remover;
    }
    stream << " removee=" << removee;
}

}}}
