/**
 * intermediate_format/events/conference/RawRemoveFromConferenceEvent.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 20668c17b966582cdc861e000869175401c4f6c94050939a3d8f117a0b97da54
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWREMOVEFROMCONFERENCEEVENT_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWREMOVEFROMCONFERENCEEVENT_H

#include "intermediate_format/events/RawEvent.h"
#include "intermediate_format/subjects/ApparentSubject.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::intermediate_format::subjects;

struct RawRemoveFromConferenceEvent : RawEvent {
public:
    unique_ptr<ApparentSubject> remover;
    unique_ptr<ApparentSubject> removee;

    RawRemoveFromConferenceEvent(IMM(ApparentTime) timestamp, uint32_t index, TAKE(ApparentSubject) removee);
    RawRemoveFromConferenceEvent(
        IMM(ApparentTime) timestamp,
        uint32_t index,
        TAKE(ApparentSubject) remover,
        TAKE(ApparentSubject) removee
    );

    virtual RawEventSubType subType() const;

    static CEDE(RawRemoveFromConferenceEvent) deserializeFromStream(QDataStream& mut_stream, bool skip_type=false);

protected:
    bool visitSubjectsImpl(IMM(visit_subjects_callback_t) callback);

    virtual void serializeDetailsToStream(QDataStream& mut_stream) const;

    virtual void writeDetailsToDebugStream(QDebug stream) const;

private:
    void sanityCheckMandatoryParameters() const;
};

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWREMOVEFROMCONFERENCEEVENT_H
