enums:
  graphics/ANSIColor:
    - black = 0
    - red = 1
    - green = 2
    - yellow = 3
    - blue = 4
    - magenta = 5
    - cyan = 6
    - white = 7
    - extended = 8

  intermediate_format/errors:
    SendMessageFailReason:
      - undetermined = 0
      - message too large
      - recipient offline
      - connection error
    StartCallFailReason:
      - undetermined = 0
      - no answer
      - peer busy
      - blocked by privacy settings as PRIVACY_BLOCKED
      - call rejected
      - connection dropped
    CurrentCallFailReason:
      - undetermined = 0
      - connection dropped
    OfferWebcamFailReason:
      - undetermined = 0
      - unsupported
    PingFailReason:
      - undetermined = 0
      - blocked/unsupported

  protocols:
    ArchiveFormat:
      - (invalid) = 0
      - Adium
      - Digsby
      - Facebook (DYI archive) as FACEBOOK_DYI
      - MSN Messenger (XML format) as MSN_MESSENGER_XML
      - Pidgin (HTML format) as PIDGIN_HTML
      - Pidgin (TXT format) as PIDGIN_TXT
      - Skype
      - WhatsApp (Email format) as WHATSAPP_EMAIL
      - Yahoo Messenger (DAT format) as YAHOO_MESSENGER_DAT

    IMProtocol:
      - (invalid) = 0
      - Digsby
      - Facebook
      - Jabber
      - MSN
      - Skype
      - WhatsApp
      - Yahoo

    IMStatus:
      - (invalid) = 0
      - available
      - away
      - idle
      - offline

    skype/SkypeChatRole:
      - (invalid) = 0
      - creator
      - master
      - helper
      - regular user
      - listener
