#!/usr/bin/env python3

import argparse
import sys
import yaml


def autogenerate_code():
    with open('autogen_config.yml', 'r') as f:
        config = yaml.load(f)
        print(config)

def main():
    parser = argparse.ArgumentParser(description='Build assistant for Uniarchive II')

    subparsers = parser.add_subparsers(title='commands', dest='command')

    subparsers.add_parser('gencode', help='Build autogenerated code')

    raw_args = parser.parse_args(sys.argv[1:])

    if raw_args.command is None:
        parser.print_usage()
        return

    if raw_args.command == 'gencode':
        autogenerate_code()

main()
