/**
 * intermediate_format/provenance/ProvenanceSubType.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 115d96319dd8266b189a9c881bdf58628e20d0fbc41df46e0d87f9d2527a507e
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_PROVENANCE_PROVENANCESUBTYPE_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_PROVENANCE_PROVENANCESUBTYPE_H

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace provenance {

enum class ProvenanceSubType {
    ARCHIVE_FILE,
    ADIUM_ARCHIVE_FILE,
    EVENT_RANGE,
    MSN_CONVERSATION,
    SKYPE_CONVERSATION,
};

QString name_for_provenance_sub_type(ProvenanceSubType type);

QDebug operator<< (QDebug stream, ProvenanceSubType type);
QDataStream& operator<< (QDataStream& mut_stream, ProvenanceSubType type);

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_PROVENANCE_PROVENANCESUBTYPE_H
