/**
 * intermediate_format/events/file_transfer/RawCancelFileTransferEvent.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 4259111187b7ad69606acd94886ff190d2af7332ec9ed2c7935ccf4d4522aefb
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWCANCELFILETRANSFEREVENT_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWCANCELFILETRANSFEREVENT_H

#include "intermediate_format/events/RawEvent.h"
#include "intermediate_format/subjects/ApparentSubject.h"
#include "intermediate_format/RawTransferredFile.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::intermediate_format::subjects;

struct RawCancelFileTransferEvent : RawEvent {
public:
    optional<RawTransferredFile> file;
    unique_ptr<ApparentSubject> actor;

    RawCancelFileTransferEvent(IMM(ApparentTime) timestamp, uint32_t index);
    RawCancelFileTransferEvent(IMM(ApparentTime) timestamp, uint32_t index, IMM(RawTransferredFile) file);

    virtual RawEventSubType subType() const;

    static CEDE(RawCancelFileTransferEvent) deserializeFromStream(QDataStream& mut_stream, bool skip_type=false);

protected:
    bool visitSubjectsImpl(IMM(visit_subjects_callback_t) callback) const;
    bool alterSubjectsImpl(IMM(alter_subjects_callback_t) callback);

    virtual void serializeDetailsToStream(QDataStream& mut_stream) const;

    virtual void writeDetailsToDebugStream(QDebug stream) const;
};

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWCANCELFILETRANSFEREVENT_H
