/**
 * intermediate_format/events/file_transfer/RawCancelFileTransferEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): acc856c2bc137e1348918231ec501cf59f34b2a85751cdf66276a497b9217b19
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/file_transfer/RawCancelFileTransferEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawCancelFileTransferEvent::RawCancelFileTransferEvent(IMM(ApparentTime) timestamp, uint index)
  : RawEvent(timestamp, index) {
}

RawCancelFileTransferEvent::RawCancelFileTransferEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    IMM(RawTransferredFile) file
) : RawEvent(timestamp, index), file(file) {
}

QString RawCancelFileTransferEvent::eventName() const {
    return "CancelFileTransfer";
}

void RawCancelFileTransferEvent::writeDetailsToDebugStream(QDebug stream) const {
    if (file) {
        stream << " file=" << *file;
    }
    if (actor) {
        stream << " actor=" << actor.get();
    }
}

}}}
