/**
 * intermediate_format/events/file_transfer/RawTransferFilesEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 46b1372106c1a9bbb0cf3ea7f6f283c25940aadc04541d8a7bf002910d3c682d
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/file_transfer/RawTransferFilesEvent.h"
#include "utils/qt/debug_extras.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawTransferFilesEvent::RawTransferFilesEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) sender,
    IMM(vector<RawTransferredFile>) files
) : RawEvent(timestamp, index), sender(move(sender)), files(files) {
    sanityCheckMandatoryParameters();
}

RawTransferFilesEvent::RawTransferFilesEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) sender,
    IMM(RawTransferredFile) file
) : RawEvent(timestamp, index), sender(move(sender)) {
    files.push_back(file);
    sanityCheckMandatoryParameters();
}

void RawTransferFilesEvent::sanityCheckMandatoryParameters() const {
    invariant(sender, "Parameter 'sender' cannot have empty value");
}

RawEventSubType RawTransferFilesEvent::subType() const {
    return RawEventSubType::TRANSFER_FILES;
}

void RawTransferFilesEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " sender=" << sender.get();
    if (recipient) {
        stream << " recipient=" << recipient.get();
    }
    if (files.size() == 1) {
        stream << " file=" << files.front();
    } else {
        stream << " files=" << files;
    }
}

}}}
