/**
 * intermediate_format/content/formatting/ANSIColorTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 16ec4acf719da423e42a37933f1fa1f9cf6434ee12832a3383025ecc362246da
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/ANSIColorTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

ANSIColorTag::ANSIColorTag(bool open, ANSIColor color) : SymmetricTag(open), color(color) {
}

QString ANSIColorTag::tagName() const {
    return "ANSICol";
}

void ANSIColorTag::writeAttributesToDebugStream(QDebug stream) const {
    stream << " " << color;
}

}}}
