/**
 * intermediate_format/content/formatting/ANSIResetTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 771fd65283d5329e62f3656ec9fbda20b4b15d333943b21de51179e00010dcc9
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/ANSIResetTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

ANSIResetTag::ANSIResetTag() : SelfClosingTag() {
}

QString ANSIResetTag::tagName() const {
    return "ANSIReset";
}

}}}
