/**
 * intermediate_format/content/formatting/BoldTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 708e1ec1550782651dd597443fac37166f83ab618b7fa5e900a204cc07fa05d8
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/BoldTag.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

using namespace uniarchive2::utils::serialization;

BoldTag::BoldTag(bool open) : StandardTag(open) {
    // Nothing else to initialize
}

RawMessageContentItemSubType BoldTag::subType() const {
    return RawMessageContentItemSubType::BOLD_TAG;
}

QString BoldTag::tagName() const {
    return "B";
}

CEDE(BoldTag) BoldTag::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    maybeDeserializeType(skip_type, mut_stream, RawMessageContentItemSubType::BOLD_TAG);

    if (!must_deserialize(mut_stream, bool)) {
        return make_unique<BoldTag>(false);
    }

    unique_ptr<BoldTag> item = make_unique<BoldTag>(true);

    return item;
}

void BoldTag::serializeOpenTagAttributesToStream(QDataStream& UNUSED mut_stream) const {
}

}}}
