/**
 * intermediate_format/content/formatting/BoldTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 42d4d2401063650c2dc3fa98700d9d50668ffe8ba8bb366ca5f45d5fe3960102
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/BoldTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

BoldTag::BoldTag(bool open) : StandardTag(open) {
}

RawMessageContentItemSubType BoldTag::subType() const {
    return RawMessageContentItemSubType::BOLD_TAG;
}

QString BoldTag::tagName() const {
    return "B";
}

}}}
