/**
 * intermediate_format/content/formatting/EmphasisTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): b015d5344369d4c15f5b39980776b64b36c082d117a0f55ec8f8b3e7c305dfd4
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/EmphasisTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

EmphasisTag::EmphasisTag(bool open) : StandardTag(open) {
}

QString EmphasisTag::tagName() const {
    return "EM";
}

}}}
