/**
 * intermediate_format/content/formatting/EmphasisTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 63e6fd2b8519f519177aac81df7924fbb1f4722d576bccabe53dbd481804ed91
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/EmphasisTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

EmphasisTag::EmphasisTag(bool open) : StandardTag(open) {
}

RawMessageContentItemSubType EmphasisTag::subType() const {
    return RawMessageContentItemSubType::EMPHASIS_TAG;
}

QString EmphasisTag::tagName() const {
    return "EM";
}

}}}
