/**
 * intermediate_format/content/formatting/ItalicTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): c15d80db7605d92118e95c29063d4d702f5bc08bae620c7cb988d771cd7cd5bb
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/ItalicTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

ItalicTag::ItalicTag(bool open) : StandardTag(open) {
}

QString ItalicTag::tagName() const {
    return "I";
}

}}}
