/**
 * intermediate_format/content/formatting/ItalicTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 275ca3a2c6e4eda2978fd9f20fa3ac2007409cf796208ad583dc7796f02e0733
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/ItalicTag.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

using namespace uniarchive2::utils::serialization;

ItalicTag::ItalicTag(bool open) : StandardTag(open) {
    // Nothing else to initialize
}

RawMessageContentItemSubType ItalicTag::subType() const {
    return RawMessageContentItemSubType::ITALIC_TAG;
}

QString ItalicTag::tagName() const {
    return "I";
}

CEDE(ItalicTag) ItalicTag::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    maybeDeserializeType(skip_type, mut_stream, RawMessageContentItemSubType::ITALIC_TAG);

    if (!must_deserialize(mut_stream, bool)) {
        return make_unique<ItalicTag>(false);
    }

    unique_ptr<ItalicTag> item = make_unique<ItalicTag>(true);

    return item;
}

void ItalicTag::serializeOpenTagAttributesToStream(QDataStream& UNUSED mut_stream) const {
}

}}}
