/**
 * intermediate_format/content/formatting/ItalicTag.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 7edd767174b989403ba9a83d4f495b18f6f1346ea1b31a566efa043765f11107
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_CONTENT_ITALICTAG_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_CONTENT_ITALICTAG_H

#include "intermediate_format/content/StandardTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

struct ItalicTag : StandardTag {
public:
    ItalicTag(bool open);

    virtual RawMessageContentItemSubType subType() const;

    virtual QString tagName() const;
};

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_CONTENT_ITALICTAG_H
