/**
 * intermediate_format/content/formatting/LinkTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): d9703aeed934bece74e1ffa8062723029d3e36bc23c5f83d3c8c003ec1ecacb6
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/LinkTag.h"
#include "utils/serialization/serialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

LinkTag::LinkTag(bool open) : StandardTag(open) {
}

LinkTag::LinkTag(IMM(QUrl) url) : StandardTag(true), url(url) {
}

RawMessageContentItemSubType LinkTag::subType() const {
    return RawMessageContentItemSubType::LINK_TAG;
}

QString LinkTag::tagName() const {
    return "Link";
}

void LinkTag::serializeOpenTagAttributesToStream(QDataStream& mut_stream) const {
    mut_stream << url;
}

void LinkTag::writeOpenTagAttributesToDebugStream(QDebug stream) const {
    if (url) {
        stream << " " << url->url();
    }
}

}}}
