/**
 * intermediate_format/content/formatting/RGBColorTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 8e9b366a7b513f95465955247f27ce7c51305508d24f2358ce0793dcefd5387f
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/RGBColorTag.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

using namespace uniarchive2::utils::serialization;

RGBColorTag::RGBColorTag(bool open, IMM(Color) color) : SymmetricTag(open), color(color) {
    // Nothing else to initialize
}

RawMessageContentItemSubType RGBColorTag::subType() const {
    return RawMessageContentItemSubType::RGB_COLOR_TAG;
}

QString RGBColorTag::tagName() const {
    return "RGBCol";
}

bool RGBColorTag::visitSubjectsImpl(IApparentSubjectVisitor& UNUSED visitor) {
    // No fields to visit
    return true;
}

CEDE(RGBColorTag) RGBColorTag::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    maybeDeserializeType(skip_type, mut_stream, RawMessageContentItemSubType::RGB_COLOR_TAG);

    bool open = must_deserialize(mut_stream, bool);
    Color color = must_deserialize(mut_stream, Color);

    unique_ptr<RGBColorTag> item = make_unique<RGBColorTag>(open, color);

    return item;
}

void RGBColorTag::serializeAttributesToStream(QDataStream& mut_stream) const {
    mut_stream << color;
}

void RGBColorTag::writeAttributesToDebugStream(QDebug stream) const {
    stream << " " << color;
}

}}}
