/**
 * intermediate_format/content/formatting/UnderlineTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): d8d63fa2c88905153b33439ab9344360839e455bfa5ddfd398a85f1fcc620008
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/UnderlineTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

UnderlineTag::UnderlineTag(bool open) : StandardTag(open) {
}

RawMessageContentItemSubType UnderlineTag::subType() const {
    return RawMessageContentItemSubType::UNDERLINE_TAG;
}

QString UnderlineTag::tagName() const {
    return "U";
}

}}}
