/**
 * intermediate_format/content/formatting/UnderlineTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 6d40d9687e4daf2b0b9848d517d9bdab2b8767c019f89064281fdbbcfed12db2
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/UnderlineTag.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

using namespace uniarchive2::utils::serialization;

UnderlineTag::UnderlineTag(bool open) : StandardTag(open) {
    // Nothing else to initialize
}

RawMessageContentItemSubType UnderlineTag::subType() const {
    return RawMessageContentItemSubType::UNDERLINE_TAG;
}

QString UnderlineTag::tagName() const {
    return "U";
}

CEDE(UnderlineTag) UnderlineTag::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    maybeDeserializeType(skip_type, mut_stream, RawMessageContentItemSubType::UNDERLINE_TAG);

    if (!must_deserialize(mut_stream, bool)) {
        return make_unique<UnderlineTag>(false);
    }

    unique_ptr<UnderlineTag> item = make_unique<UnderlineTag>(true);

    return item;
}

void UnderlineTag::serializeOpenTagAttributesToStream(QDataStream& UNUSED mut_stream) const {
    // No fields to serialize
}

void UnderlineTag::writeOpenTagAttributesToDebugStream(QDebug UNUSED stream) const {
    // No fields to write
}

}}}
