/**
 * intermediate_format/content/formatting/YahooFadeTag.cpp
 *
 * WARNING: This file is partially autogenerated. Edit only the custom sections, or autogen_config.yml and re-generate.
 * Codegen hash (sha256): 4cd280a01d7b8f38acfbd4ec99350a78d02cb2537e249668dbe56c76ac37ef80
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/YahooFadeTag.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

YahooFadeTag::YahooFadeTag(bool open) : StandardTag(open) {
}

YahooFadeTag::YahooFadeTag(IMM(vector<Color>) colors) : StandardTag(true), colors(colors) {
}

QString YahooFadeTag::tagName() const {
    return "Fade";
}

void YahooFadeTag::writeOpenTagAttributesToDebugStream(QDebug stream) const {
    // BEGIN CUSTOM SECTION: Debug write method
    if (colors) {
        stream << " " << colors->at(0);
        if (colors->size() > 1) {
            stream << "," << colors->at(1);
        }
        if (colors->size() > 2) {
            stream << "...";
        }
    }
    // END CUSTOM SECTION: Debug write method
}

}}}
