/**
 * intermediate_format/content/formatting/YahooAltTag.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): dbcddc10521c1afc4321d97aa3bc349809e0c57d0ee20e0af188cd520b108984
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/formatting/YahooAltTag.h"
#include "utils/qt/debug_extras.h"
#include "utils/serialization/deserialization_helpers.h"
#include "utils/serialization/serialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

using namespace uniarchive2::utils::serialization;

YahooAltTag::YahooAltTag(IMM(Color) color1, IMM(Color) color2) : StandardTag(true), color1(color1), color2(color2) {
}

YahooAltTag::YahooAltTag() : StandardTag(false) {
}

RawMessageContentItemSubType YahooAltTag::subType() const {
    return RawMessageContentItemSubType::YAHOO_ALT_TAG;
}

QString YahooAltTag::tagName() const {
    return "Alt";
}

CEDE(YahooAltTag) YahooAltTag::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    invariant_violation("YahooAltTag deserialization not yet implemented");
}

void YahooAltTag::serializeOpenTagAttributesToStream(QDataStream& mut_stream) const {
    mut_stream << *color1 << *color2;
}

void YahooAltTag::writeOpenTagAttributesToDebugStream(QDebug stream) const {
    stream << " " << color1 << " " << color2;
}

}}}
