/**
 * intermediate_format/events/friending/RawContactDeleteEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 28607dfd869a0e7a558557c993aef0a9beaf53e0f27963dd764438d0ff136e40
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/friending/RawContactDeleteEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawContactDeleteEvent::RawContactDeleteEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) deleter,
    TAKE(ApparentSubject) deletee
) : RawEvent(timestamp, index), deleter(move(deleter)), deletee(move(deletee)) {
}

QString RawContactDeleteEvent::eventName() const {
    return "ContactDelete";
}

void RawContactDeleteEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " deleter=" << deleter.get() << " deletee=" << deletee.get();
}

}}}
