/**
 * intermediate_format/ApparentTimeReference.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 449e9c550ea49fe41f64a554dfeb35e3182a78b6c27cdb56f49d13a854ef586c
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_APPARENTTIMEREFERENCE_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_APPARENTTIMEREFERENCE_H

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format {

enum class ApparentTimeReference {
    UNKNOWN,
    LOCAL_TIME, // The local time when the conversation was recorded
    SPECIFIED, // At least one of UTC offset, timezone abbreviation or timezone are specified
};

QString name_for_apparent_time_reference(ApparentTimeReference reference);

QDebug operator<< (QDebug stream, ApparentTimeReference reference);
QDataStream& operator<< (QDataStream& mut_stream, ApparentTimeReference reference);

}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_APPARENTTIMEREFERENCE_H
