/**
 * intermediate_format/ApparentTimeReference.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 4387e1baf35cab61059b12bc99236f52014bfdaceb7072d7d752408add7833e9
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/ApparentTimeReference.h"
#include "utils/qt/shortcuts.h"
#include "utils/serialization/deserialization_helpers.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format {

using namespace uniarchive2::utils::serialization;

QString name_for_apparent_time_reference(ApparentTimeReference reference) {
    switch (reference) {
        case ApparentTimeReference::UNKNOWN:
            return "unknown";
        case ApparentTimeReference::LOCAL_TIME:
            return "local time";
        case ApparentTimeReference::SPECIFIED:
            return "specified";
    }

    invariant_violation("Invalid ApparentTimeReference value (%lld)", (int64_t)reference);
}

QDebug operator<< (QDebug stream, ApparentTimeReference reference) {
    stream << QP(name_for_apparent_time_reference(reference));

    return stream;
}

QDataStream& operator>> (QDataStream& mut_stream, ApparentTimeReference& mut_reference) {
    uint8_t code = must_deserialize(mut_stream, uint8_t);

    switch ((ApparentTimeReference)code) {
        case ApparentTimeReference::UNKNOWN:
        case ApparentTimeReference::LOCAL_TIME:
        case ApparentTimeReference::SPECIFIED:
            mut_reference = (ApparentTimeReference)code;
            break;
        default:
            invariant_violation("Invalid deserialized ApparentTimeReference value (%lld)", (int64_t)code);
    }

    return mut_stream;
}

QDataStream& operator<< (QDataStream& mut_stream, ApparentTimeReference reference) {
    mut_stream << (uint8_t)reference;

    return mut_stream;
}

}}
