/**
 * intermediate_format/ApparentTimeReference.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): bcec3f4aa801faa08c6448e801f9aa18e8cef28b78d6dcb71b87fb70b6b598b3
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/ApparentTimeReference.h"
#include "utils/qt/shortcuts.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format {

QString name_for_apparent_time_reference(ApparentTimeReference reference) {
    switch (reference) {
        case ApparentTimeReference::UNKNOWN:
            return "unknown";
        case ApparentTimeReference::LOCAL_TIME:
            return "local time";
        case ApparentTimeReference::SPECIFIED:
            return "specified";
    }

    invariant_violation("Invalid ApparentTimeReference value (%d)", reference);
}

QDebug operator<< (QDebug stream, ApparentTimeReference reference) {
    stream << QP(name_for_apparent_time_reference(reference));

    return stream;
}

QDataStream& operator<< (QDataStream& mut_stream, ApparentTimeReference reference) {
    mut_stream << (uint32_t)reference;

    return mut_stream;
}

}}
