/**
 * intermediate_format/ApparentTimeReference.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 587f871bb9088bc1e82beee9391e9e5792aee382f0f8e885a1f32c95b90985e7
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_APPARENTTIMEREFERENCE_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_APPARENTTIMEREFERENCE_H

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format {

enum class ApparentTimeReference : uint8_t {
    UNKNOWN,
    LOCAL_TIME, // The local time when the conversation was recorded
    SPECIFIED, // At least one of UTC offset, timezone abbreviation or timezone are specified
};

QString name_for_apparent_time_reference(ApparentTimeReference reference);

QDebug operator<< (QDebug stream, ApparentTimeReference reference);

QDataStream& operator>> (QDataStream& mut_stream, ApparentTimeReference& mut_reference);
QDataStream& operator<< (QDataStream& mut_stream, ApparentTimeReference reference);

}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_APPARENTTIMEREFERENCE_H
