/**
 * intermediate_format/content/LineBreak.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 05cdaa1fc610eca5a5c4631e2d5d0146aa04c4167aafef71e5539401f3e0396f
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/LineBreak.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

LineBreak::LineBreak() : RawMessageContentItem() {
}

RawMessageContentItemSubType LineBreak::subType() const {
    return RawMessageContentItemSubType::LINE_BREAK;
}

void LineBreak::writeToDebugStreamImpl(QDebug stream) const {
    stream << "[BRK]";
}

}}}
