/**
 * intermediate_format/content/MediaAttachment.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): c49a238ca6e6a88e3ad23d74112c82f02270c119056d3aa236dc14b566860122
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/MediaAttachment.h"
#include "utils/qt/debug_extras.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

MediaAttachment::MediaAttachment() : RawMessageContentItem() {
}

RawMessageContentItemSubType MediaAttachment::subType() const {
    return RawMessageContentItemSubType::MEDIA_ATTACHMENT;
}

void MediaAttachment::writeToDebugStreamImpl(QDebug stream) const {
    stream << "[Media";
    if (filename) {
        stream << " filename=" << filename;
    }
    if (error) {
        stream << " error=" << error;
    }
    stream << "]";
}

}}}
