/**
 * intermediate_format/content/SkypeQuote.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): fd00a63bcddb397a46d7fee3e4dd67df3f96128f006c156bb65f0f61c2288f3f
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/SkypeQuote.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

SkypeQuote::SkypeQuote(
    IMM(QString) conversation_id,
    IMM(QString) message_guid,
    TAKE(ApparentSubject) author,
    IMM(ApparentTime) time,
    IMM(QString) legacy_header,
    RawMessageContent&& content
) : RawMessageContentItem(), quotedMessageConversationID(conversation_id), quotedMessageGUID(message_guid),
    quotedMessageAuthor(move(author)), quotedMessageTime(time), legacyHeader(legacy_header), content(move(content)) {
    sanityCheckMandatoryParameters();
}

void SkypeQuote::sanityCheckMandatoryParameters() const {
    invariant(quotedMessageAuthor, "Parameter 'author' cannot have empty value");
}

RawMessageContentItemSubType SkypeQuote::subType() const {
    return RawMessageContentItemSubType::SKYPE_QUOTE;
}

void SkypeQuote::writeToDebugStreamImpl(QDebug stream) const {
    stream << "[SkypeQuote";
    stream << " conversation_id=" << quotedMessageConversationID << " message_guid=" << quotedMessageGUID;
    stream << " author=" << quotedMessageAuthor.get() << " time=" << quotedMessageTime;
    stream << " legacy_header=" << legacyHeader << " content=" << content;
    stream << "]";
}

}}}
