/**
 * intermediate_format/content/SkypeQuote.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): c6a71307b1d60b47b76f40e9d4ac58efb0056401ab4a28b134fe061e0aae4ef0
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_CONTENT_SKYPEQUOTE_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_CONTENT_SKYPEQUOTE_H

#include "intermediate_format/content/RawMessageContent.h"
#include "intermediate_format/content/RawMessageContentItem.h"
#include "intermediate_format/subjects/ApparentSubject.h"
#include "intermediate_format/ApparentTime.h"
#include "utils/language/shortcuts.h"

#include <QDataStream>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace content {

using namespace uniarchive2::intermediate_format::subjects;

struct SkypeQuote : RawMessageContentItem {
public:
    QString quotedMessageConversationID;
    QString quotedMessageGUID;
    unique_ptr<ApparentSubject> quotedMessageAuthor;
    ApparentTime quotedMessageTime;
    QString legacyHeader;
    RawMessageContent content;

    SkypeQuote(
        IMM(QString) conversation_id,
        IMM(QString) message_guid,
        TAKE(ApparentSubject) author,
        IMM(ApparentTime) time,
        IMM(QString) legacy_header,
        RawMessageContent&& content
    );

    virtual RawMessageContentItemSubType subType() const;

    static CEDE(SkypeQuote) deserializeFromStream(QDataStream& mut_stream, bool skip_type=false);

protected:
    bool visitSubjectsImpl(IMM(visit_subjects_callback_t) callback);

    virtual void serializeToStreamImpl(QDataStream& mut_stream) const;

    virtual void writeToDebugStreamImpl(QDebug stream) const;

private:
    void sanityCheckMandatoryParameters() const;
};

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_CONTENT_SKYPEQUOTE_H
