/**
 * graphics/ANSIColor.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 560da8b984a330a4083268dca6d174ff5e0d5bacc94e3054f70dfa30cce72ee5
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_GRAPHICS_ANSICOLOR_H
#define UNIARCHIVE2_GRAPHICS_ANSICOLOR_H

#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace graphics {

enum class ANSIColor {
    BLACK = 0,
    RED = 1,
    GREEN = 2,
    YELLOW = 3,
    BLUE = 4,
    MAGENTA = 5,
    CYAN = 6,
    WHITE = 7,
    EXTENDED = 8,
};

QString name_for_ansi_color(ANSIColor color);

QDebug operator<< (QDebug stream, ANSIColor color);

}}

#endif //UNIARCHIVE2_GRAPHICS_ANSICOLOR_H
