/**
 * graphics/ANSIColor.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 1ea02a3afc03f81939807c01e7ac0047b668fb19df5d5a6bd656d3b556abf102
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_GRAPHICS_ANSICOLOR_H
#define UNIARCHIVE2_GRAPHICS_ANSICOLOR_H

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace graphics {

enum class ANSIColor : uint8_t {
    BLACK = 0,
    RED = 1,
    GREEN = 2,
    YELLOW = 3,
    BLUE = 4,
    MAGENTA = 5,
    CYAN = 6,
    WHITE = 7,
    EXTENDED = 8,
};

QString name_for_ansi_color(ANSIColor color);

QDebug operator<< (QDebug stream, ANSIColor color);
QDataStream& operator<< (QDataStream& mut_stream, ANSIColor color);

}}

#endif //UNIARCHIVE2_GRAPHICS_ANSICOLOR_H
