/**
 * graphics/ANSIColor.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 0636fc9371b0d815bc62fc6df387e1535887410d6270dc084853af5dc2620f41
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "graphics/ANSIColor.h"
#include "utils/qt/shortcuts.h"
#include "utils/serialization/deserialization_helpers.h"

#include <QtDebug>

namespace uniarchive2 { namespace graphics {

using namespace uniarchive2::utils::serialization;

QString name_for_ansi_color(ANSIColor color) {
    switch (color) {
        case ANSIColor::BLACK:
            return "black";
        case ANSIColor::RED:
            return "red";
        case ANSIColor::GREEN:
            return "green";
        case ANSIColor::YELLOW:
            return "yellow";
        case ANSIColor::BLUE:
            return "blue";
        case ANSIColor::MAGENTA:
            return "magenta";
        case ANSIColor::CYAN:
            return "cyan";
        case ANSIColor::WHITE:
            return "white";
        case ANSIColor::EXTENDED:
            return "extended";
    }

    invariant_violation("Invalid ANSIColor value (%lld)", (int64_t)color);
}

QDebug operator<< (QDebug stream, ANSIColor color) {
    stream << QP(name_for_ansi_color(color));

    return stream;
}

QDataStream& operator>> (QDataStream& mut_stream, ANSIColor& mut_color) {
    uint8_t code = must_deserialize(mut_stream, uint8_t);

    switch ((ANSIColor)code) {
        case ANSIColor::BLACK:
        case ANSIColor::RED:
        case ANSIColor::GREEN:
        case ANSIColor::YELLOW:
        case ANSIColor::BLUE:
        case ANSIColor::MAGENTA:
        case ANSIColor::CYAN:
        case ANSIColor::WHITE:
        case ANSIColor::EXTENDED:
            mut_color = (ANSIColor)code;
            break;
        default:
            invariant_violation("Invalid deserialized ANSIColor value (%lld)", (int64_t)code);
    }

    return mut_stream;
}

QDataStream& operator<< (QDataStream& mut_stream, ANSIColor color) {
    mut_stream << (uint8_t)color;

    return mut_stream;
}

}}
