/**
 * intermediate_format/content/symbols/SkypeEmoticon.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 8d6d1e91a55d37eeb8755fdaee3e8d5483242d082928b7ad8ca37f7bf36f9999
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/content/symbols/SkypeEmoticon.h"

namespace uniarchive2 { namespace intermediate_format { namespace content {

SkypeEmoticon::SkypeEmoticon(IMM(QString) semantics, IMM(QString) text_equivalent)
  : RawMessageContentItem(), semantics(semantics), textEquivalent(text_equivalent) {
}

RawMessageContentItemSubType SkypeEmoticon::subType() const {
    return RawMessageContentItemSubType::SKYPE_EMOTICON;
}

void SkypeEmoticon::writeToDebugStreamImpl(QDebug stream) const {
    stream << "[SkypeEmoticon";
    stream << " semantics=" << semantics << " text_equivalent=" << textEquivalent;
    stream << "]";
}

}}}
