/**
 * intermediate_format/subjects/ApparentSubjectSubType.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): abc0caef6f3deadabe2b5d947462b2f846d41204612e6eab536096e7408464fa
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_SUBJECTS_APPARENTSUBJECTSUBTYPE_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_SUBJECTS_APPARENTSUBJECTSUBTYPE_H

#include "utils/language/shortcuts.h"

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace subjects {

enum class ApparentSubjectSubType : uint8_t {
    IMPLICIT,
    SCREEN_NAME,
    ACCOUNT,
    FULLY_SPECIFIED,
    RESOLVED,
};

QString name_for_apparent_subject_sub_type(ApparentSubjectSubType type);

QString symbol_for_apparent_subject_sub_type(ApparentSubjectSubType type);
ApparentSubjectSubType apparent_subject_sub_type_from_symbol(IMM(QString) symbol);

QDebug operator<< (QDebug stream, ApparentSubjectSubType type);

QDataStream& operator>> (QDataStream& mut_stream, ApparentSubjectSubType& mut_type);
QDataStream& operator<< (QDataStream& mut_stream, ApparentSubjectSubType type);

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_SUBJECTS_APPARENTSUBJECTSUBTYPE_H
