/**
 * intermediate_format/subjects/ApparentSubjectSubType.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 130a0bddcfc3128c3ddaf782e37998d94b05f11646a06d5104faa45401c3a31f
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/subjects/ApparentSubjectSubType.h"
#include "utils/qt/shortcuts.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace subjects {

QString name_for_apparent_subject_sub_type(ApparentSubjectSubType type) {
    switch (type) {
        case ApparentSubjectSubType::IMPLICIT:
            return "Implicit";
        case ApparentSubjectSubType::SCREEN_NAME:
            return "ScreenName";
        case ApparentSubjectSubType::ACCOUNT:
            return "Account";
        case ApparentSubjectSubType::FULLY_SPECIFIED:
            return "FullySpecified";
    }

    invariant_violation("Invalid ApparentSubjectSubType value (%d)", type);
}

QDebug operator<< (QDebug stream, ApparentSubjectSubType type) {
    stream << QP(name_for_apparent_subject_sub_type(type));

    return stream;
}

QDataStream& operator<< (QDataStream& mut_stream, ApparentSubjectSubType type) {
    mut_stream << (quint32)type;

    return mut_stream;
}

}}}
