/**
 * intermediate_format/subjects/ImplicitSubjectKind.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): d9a600f7957e2a2d74aede296b3efd40526753d3dec3eb8ac874a9e4991c3a8d
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/subjects/ImplicitSubjectKind.h"
#include "utils/qt/shortcuts.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace subjects {

QString name_for_implicit_subject_kind(ImplicitSubjectKind kind) {
    switch (kind) {
        case ImplicitSubjectKind::INVALID:
            return "(invalid)";
        case ImplicitSubjectKind::IDENTITY:
            return "identity";
        case ImplicitSubjectKind::FILE_RECEIVER:
            return "file receiver";
    }

    invariant_violation("Invalid ImplicitSubjectKind value (%d)", kind);
}

QDebug operator<< (QDebug stream, ImplicitSubjectKind kind) {
    stream << QP(name_for_implicit_subject_kind(kind));

    return stream;
}

QDataStream& operator<< (QDataStream& mut_stream, ImplicitSubjectKind kind) {
    mut_stream << (uint32_t)kind;

    return mut_stream;
}

}}}
