/**
 * intermediate_format/events/RawChangeScreenNameEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 7ac8aff5c9b44280f95f72d076762589aef2808678b1d971e7e94dee687d5dda
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/RawChangeScreenNameEvent.h"
#include "utils/qt/debug_extras.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawChangeScreenNameEvent::RawChangeScreenNameEvent(
    IMM(ApparentTime) timestamp,
    uint32_t index,
    TAKE(ApparentSubject) from,
    TAKE(ApparentSubject) to
) : RawEvent(timestamp, index), from(move(from)), to(move(to)) {
    sanityCheckMandatoryParameters();
}

void RawChangeScreenNameEvent::sanityCheckMandatoryParameters() const {
    invariant(from, "Parameter 'from' cannot have empty value");
    invariant(to, "Parameter 'to' cannot have empty value");
}

RawEventSubType RawChangeScreenNameEvent::subType() const {
    return RawEventSubType::CHANGE_SCREEN_NAME;
}

void RawChangeScreenNameEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    // TODO: add field serialization code
}

void RawChangeScreenNameEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " from=" << from << " to=" << to;
}

}}}
