/**
 * intermediate_format/events/RawEvent.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): b11bdc49fef42e7feda200f59878a741c45f37ac04b1db6a9b2f40428eb1f10d
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWEVENT_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWEVENT_H

#include "intermediate_format/events/RawEventSubType.h"
#include "intermediate_format/subjects/visitor/IApparentSubjectVisitable.h"
#include "intermediate_format/ApparentTime.h"
#include "utils/external_libs/optional.hpp"
#include "utils/language/shortcuts.h"
#include "utils/polymorphics/StandardPolymorphic.h"

#include <QByteArray>
#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace std::experimental;
using namespace uniarchive2::intermediate_format::subjects;
using namespace uniarchive2::utils::polymorphics;

struct RawEvent : StandardPolymorphic<RawEventSubType>, IApparentSubjectVisitable {
public:
    ApparentTime timestamp;
    uint32_t indexInConversation;

    optional<QByteArray> skypeGUID;

    RawEvent(IMM(ApparentTime) timestamp, uint32_t index);

    virtual QString eventName() const;

    bool visitSubjects(IMM(visit_subjects_callback_t) callback);

    static CEDE(RawEvent) deserializeFromStream(QDataStream& mut_stream);

    void writeToDebugStream(QDebug stream) const;

protected:
    virtual bool visitSubjectsImpl(IMM(visit_subjects_callback_t) callback) = 0;

    virtual void serializeToStreamImpl(QDataStream& mut_stream) const;
    virtual void serializeDetailsToStream(QDataStream& mut_stream) const = 0;

    virtual void writeDetailsToDebugStream(QDebug stream) const = 0;
};

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_EVENTS_RAWEVENT_H
