/**
 * intermediate_format/events/RawEditedPreviousMessageEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 2eb7be80efa9e1a4d700a8bcd006c762a232233f1e54f7b0204c6a29a4c95dc6
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/RawEditedPreviousMessageEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawEditedPreviousMessageEvent::RawEditedPreviousMessageEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) subject
) : RawEvent(timestamp, index), subject(move(subject)) {
    sanityCheckMandatoryParameters();
}

void RawEditedPreviousMessageEvent::sanityCheckMandatoryParameters() const {
    invariant(subject, "Parameter 'subject' cannot have empty value");
}

RawEventSubType RawEditedPreviousMessageEvent::subType() const {
    return RawEventSubType::EDITED_PREVIOUS_MESSAGE;
}

QString RawEditedPreviousMessageEvent::eventName() const {
    return "EditedPreviousMessage";
}

void RawEditedPreviousMessageEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " subject=" << subject.get();
}

}}}
