/**
 * intermediate_format/events/RawMessageEvent.cpp
 *
 * WARNING: This file is partially autogenerated. Edit only the custom sections, or autogen_config.yml and re-generate.
 * Codegen hash (sha256): 871b3ffbc91ab2c1211014de64c8010675a2535a22b9e457b9bbd061e72318c2
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/RawMessageEvent.h"
#include "utils/serialization/deserialization_helpers.h"
#include "utils/serialization/serialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::utils::serialization;

RawMessageEvent::RawMessageEvent(
    IMM(ApparentTime) timestamp,
    uint32_t index,
    TAKE(ApparentSubject) sender,
    RawMessageContent&& content
) : RawFailableEvent(timestamp, index), sender(move(sender)), content(move(content)) {
    sanityCheckMandatoryParameters();
}

void RawMessageEvent::sanityCheckMandatoryParameters() const {
    invariant(sender, "Parameter 'sender' cannot have empty value");
}

RawEventSubType RawMessageEvent::subType() const {
    return RawEventSubType::MESSAGE;
}

CEDE(RawMessageEvent) RawMessageEvent::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    invariant_violation("RawMessageEvent deserialization not yet implemented");
}

void RawMessageEvent::serializeFailableEventDetailsToStream(QDataStream& mut_stream) const {
    mut_stream << sender;
    serialize_optional_unique_ptr(mut_stream, receiver);
    mut_stream << content << isOffline << isAction << isEdited;
    serialize_optional_unique_ptr(mut_stream, editedBy);
    mut_stream << timeEdited;
}

void RawMessageEvent::writeFailableEventDetailsToDebugStream(QDebug stream) const {
    // BEGIN CUSTOM SECTION: Debug write method
    if (isOffline) {
        stream << " OFFLINE";
    }
    if (isEdited) {
        stream << " EDITED";
        if (editedBy || timeEdited) {
            stream << "(";
            if (editedBy) {
                stream << "edited_by=" << editedBy.get();
            }
            if (timeEdited) {
                stream << (editedBy ? " " : "") << "time_edited=" << *timeEdited;
            }
            stream << ")";
        }
    }
    if (isAction) {
        stream << " ACTION";
    }
    stream << " sender=" << sender.get();
    if (receiver) {
        stream << " receiver=" << receiver.get();
    }
    stream << " content=" << content;
    // END CUSTOM SECTION: Debug write method
}

}}}
