/**
 * intermediate_format/events/RawUninterpretedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 970349510e076876088208d4cd7b2cc2fa04b64707df043d1028978a1b5885e7
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/RawUninterpretedEvent.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::utils::serialization;

RawUninterpretedEvent::RawUninterpretedEvent(IMM(ApparentTime) timestamp, uint32_t index, IMM(QByteArray) raw_data)
  : RawEvent(timestamp, index), rawData(raw_data) {
}

RawEventSubType RawUninterpretedEvent::subType() const {
    return RawEventSubType::UNINTERPRETED;
}

CEDE(RawUninterpretedEvent) RawUninterpretedEvent::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    invariant_violation("RawUninterpretedEvent deserialization not yet implemented");
}

void RawUninterpretedEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    mut_stream << rawData;
}

void RawUninterpretedEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " raw_data=" << rawData;
}

}}}
