/**
 * intermediate_format/events/RawUninterpretedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): cefe5d58e90c10074e6803dc58c798d80cc252956523ad129b43798e8a2da554
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/RawUninterpretedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawUninterpretedEvent::RawUninterpretedEvent(IMM(ApparentTime) timestamp, uint index, IMM(QByteArray) raw_data)
  : RawEvent(timestamp, index), rawData(raw_data) {
}

RawEventSubType RawUninterpretedEvent::subType() const {
    return RawEventSubType::UNINTERPRETED;
}

void RawUninterpretedEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " raw_data=" << rawData;
}

}}}
