/**
 * intermediate_format/events/RawUninterpretedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): a3092ba49612709014b5f48bf14ccca639564a9da1d8877a8367a4d58595b980
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/RawUninterpretedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawUninterpretedEvent::RawUninterpretedEvent(IMM(ApparentTime) timestamp, uint32_t index, IMM(QByteArray) raw_data)
  : RawEvent(timestamp, index), rawData(raw_data) {
}

RawEventSubType RawUninterpretedEvent::subType() const {
    return RawEventSubType::UNINTERPRETED;
}

void RawUninterpretedEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    // TODO: add field serialization code
}

void RawUninterpretedEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " raw_data=" << rawData;
}

}}}
