/**
 * intermediate_format/events/conversation/RawJoinConversationEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): ae9e7720787c5fcb1aecbb13a0b5a94e27df3ffcd4f925a62797099cec5296db
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conversation/RawJoinConversationEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawJoinConversationEvent::RawJoinConversationEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) subject
) : RawEvent(timestamp, index), subject(move(subject)) {
    sanityCheckMandatoryParameters();
}

void RawJoinConversationEvent::sanityCheckMandatoryParameters() const {
    invariant(subject, "Parameter 'subject' cannot have empty value");
}

QString RawJoinConversationEvent::eventName() const {
    return "JoinConversation";
}

void RawJoinConversationEvent::writeDetailsToDebugStream(QDebug stream) const {
    stream << " subject=" << subject.get();
}

}}}
