/**
 * intermediate_format/events/conversation/RawStartConversationEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 1c01993edc3ab8e09bce5088cbdcfd237c95ceacc3d943e5661288fe151c9347
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/conversation/RawStartConversationEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawStartConversationEvent::RawStartConversationEvent(IMM(ApparentTime) timestamp, uint index)
  : RawEvent(timestamp, index) {
}

RawStartConversationEvent::RawStartConversationEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) initiator
) : RawEvent(timestamp, index), initiator(move(initiator)) {
    invariant(this->initiator, "Parameter 'initiator' cannot have empty value");
}

RawStartConversationEvent::RawStartConversationEvent(
    IMM(ApparentTime) timestamp,
    uint index,
    TAKE(ApparentSubject) initiator,
    TAKE(ApparentSubject) peer
) : RawEvent(timestamp, index), initiator(move(initiator)), peer(move(peer)) {
    invariant(this->initiator, "Parameter 'initiator' cannot have empty value");
    invariant(this->peer, "Parameter 'peer' cannot have empty value");
}

RawEventSubType RawStartConversationEvent::subType() const {
    return RawEventSubType::START_CONVERSATION;
}

void RawStartConversationEvent::serializeDetailsToStream(QDataStream& mut_stream) const {
    // TODO: add field serialization code
}

void RawStartConversationEvent::writeDetailsToDebugStream(QDebug stream) const {
    if (initiator) {
        stream << " initiator=" << initiator.get();
    }
    if (peer) {
        stream << " peer=" << peer.get();
    }
}

}}}
