/**
 * intermediate_format/events/system/RawEEEncryptionAnnouncementEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 5c48c47d119c1e1cb771f4f9a2e65796af7ece197170d51cc535b1e1b9c889e8
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawEEEncryptionAnnouncementEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawEEEncryptionAnnouncementEvent::RawEEEncryptionAnnouncementEvent(IMM(ApparentTime) timestamp, uint index)
  : RawEvent(timestamp, index) {
}

QString RawEEEncryptionAnnouncementEvent::eventName() const {
    return "EEEncryptionAnnouncement";
}

void RawEEEncryptionAnnouncementEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
