/**
 * intermediate_format/events/system/RawEEEncryptionAnnouncementEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 0402a41511630a20dcbcb0bf7d27c30ff8ff57f7bbbbd0e6939e38fa5fc7f2b3
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawEEEncryptionAnnouncementEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawEEEncryptionAnnouncementEvent::RawEEEncryptionAnnouncementEvent(IMM(ApparentTime) timestamp, uint index)
  : RawEvent(timestamp, index) {
}

RawEventSubType RawEEEncryptionAnnouncementEvent::subType() const {
    return RawEventSubType::EE_ENCRYPTION_ANNOUNCEMENT;
}

void RawEEEncryptionAnnouncementEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
