/**
 * intermediate_format/events/system/RawLoggingStartedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 88948e10394342a25ec5178f56170440283dbd6588f23d222f7fd0bab32e1146
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawLoggingStartedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawLoggingStartedEvent::RawLoggingStartedEvent(IMM(ApparentTime) timestamp, uint index) : RawEvent(timestamp, index) {
}

QString RawLoggingStartedEvent::eventName() const {
    return "LoggingStarted";
}

void RawLoggingStartedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
