/**
 * intermediate_format/events/system/RawLoggingStartedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 55660d7d625b003ed91aecff2b2148b363f80d712c550c6eaf27ee8d9e421307
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawLoggingStartedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawLoggingStartedEvent::RawLoggingStartedEvent(IMM(ApparentTime) timestamp, uint32_t index)
  : RawEvent(timestamp, index) {
}

RawEventSubType RawLoggingStartedEvent::subType() const {
    return RawEventSubType::LOGGING_STARTED;
}

void RawLoggingStartedEvent::serializeDetailsToStream(QDataStream& UNUSED mut_stream) const {
}

void RawLoggingStartedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
