/**
 * intermediate_format/events/system/RawLoggingStoppedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 34306e6ea59b4a3395d5e4a8d623e687258ab0d5d7ca2d35d4c1fe30ccf00a16
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawLoggingStoppedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawLoggingStoppedEvent::RawLoggingStoppedEvent(IMM(ApparentTime) timestamp, uint index) : RawEvent(timestamp, index) {
}

RawEventSubType RawLoggingStoppedEvent::subType() const {
    return RawEventSubType::LOGGING_STOPPED;
}

void RawLoggingStoppedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
