/**
 * intermediate_format/events/system/RawWindowOpenedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 2b9b877fe5189171fd9d3fe8922656d6576246fbd91718d7838de61094256d37
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawWindowOpenedEvent.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::utils::serialization;

RawWindowOpenedEvent::RawWindowOpenedEvent(IMM(ApparentTime) timestamp, uint32_t index) : RawEvent(timestamp, index) {
    // Nothing else to initialize
}

RawEventSubType RawWindowOpenedEvent::subType() const {
    return RawEventSubType::WINDOW_OPENED;
}

void RawWindowOpenedEvent::visitSubjectsImpl(ApparentSubjectVisitor& UNUSED visitor) {
    // No fields to visit
}

CEDE(RawWindowOpenedEvent) RawWindowOpenedEvent::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    maybeDeserializeType(skip_type, mut_stream, RawEventSubType::WINDOW_OPENED);

    ApparentTime timestamp = must_deserialize(mut_stream, ApparentTime);
    uint32_t index = must_deserialize(mut_stream, uint32_t);
    optional<QByteArray> skype_guid = must_deserialize(mut_stream, optional<QByteArray>);

    unique_ptr<RawWindowOpenedEvent> event = make_unique<RawWindowOpenedEvent>(timestamp, index);
    event->skypeGUID = skype_guid;

    return event;
}

void RawWindowOpenedEvent::serializeDetailsToStream(QDataStream& UNUSED mut_stream) const {
    // No fields to serialize
}

void RawWindowOpenedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
    // No fields to write
}

}}}
