/**
 * intermediate_format/events/system/RawWindowClosedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 24dde6d5c8415a2072f7788a218021722b8e795fd6bc2fd2fe7ab26962eb9c61
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawWindowClosedEvent.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::utils::serialization;

RawWindowClosedEvent::RawWindowClosedEvent(IMM(ApparentTime) timestamp, uint32_t index) : RawEvent(timestamp, index) {
    // Nothing else to initialize
}

RawEventSubType RawWindowClosedEvent::subType() const {
    return RawEventSubType::WINDOW_CLOSED;
}

bool RawWindowClosedEvent::visitSubjectsImpl(IMM(visit_subjects_callback_t) UNUSED callback) {
    // No fields to visit
    return true;
}

CEDE(RawWindowClosedEvent) RawWindowClosedEvent::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    maybeDeserializeType(skip_type, mut_stream, RawEventSubType::WINDOW_CLOSED);

    ApparentTime timestamp = must_deserialize(mut_stream, ApparentTime);
    uint32_t index = must_deserialize(mut_stream, uint32_t);
    optional<QByteArray> skype_guid = must_deserialize(mut_stream, optional<QByteArray>);

    unique_ptr<RawWindowClosedEvent> event = make_unique<RawWindowClosedEvent>(timestamp, index);
    event->skypeGUID = skype_guid;

    return event;
}

void RawWindowClosedEvent::serializeDetailsToStream(QDataStream& UNUSED mut_stream) const {
    // No fields to serialize
}

void RawWindowClosedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
    // No fields to write
}

}}}
