/**
 * intermediate_format/events/system/RawWindowClosedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 77f150062abbff0f5f7c935c63c22b7fd04b62427ca7694ab2b62805c723563b
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawWindowClosedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawWindowClosedEvent::RawWindowClosedEvent(IMM(ApparentTime) timestamp, uint index) : RawEvent(timestamp, index) {
}

RawEventSubType RawWindowClosedEvent::subType() const {
    return RawEventSubType::WINDOW_CLOSED;
}

void RawWindowClosedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
