/**
 * intermediate_format/events/system/RawWindowOpenedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 1753582ea226dce395e3d409e9c142f0b4f9046fc1751714addce9f929dbd365
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawWindowOpenedEvent.h"
#include "utils/serialization/deserialization_helpers.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

using namespace uniarchive2::utils::serialization;

RawWindowOpenedEvent::RawWindowOpenedEvent(IMM(ApparentTime) timestamp, uint32_t index) : RawEvent(timestamp, index) {
}

RawEventSubType RawWindowOpenedEvent::subType() const {
    return RawEventSubType::WINDOW_OPENED;
}

CEDE(RawWindowOpenedEvent) RawWindowOpenedEvent::deserializeFromStream(QDataStream& mut_stream, bool skip_type) {
    invariant_violation("RawWindowOpenedEvent deserialization not yet implemented");
}

void RawWindowOpenedEvent::serializeDetailsToStream(QDataStream& UNUSED mut_stream) const {
}

void RawWindowOpenedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
