/**
 * intermediate_format/events/system/RawWindowClosedEvent.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 63982141a75c13e3df8db6c53e1c9712367e9c0ed6b8a4c502818d06d72804e4
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/events/system/RawWindowClosedEvent.h"

namespace uniarchive2 { namespace intermediate_format { namespace events {

RawWindowClosedEvent::RawWindowClosedEvent(IMM(ApparentTime) timestamp, uint index) : RawEvent(timestamp, index) {
}

QString RawWindowClosedEvent::eventName() const {
    return "WindowClosed";
}

void RawWindowClosedEvent::writeDetailsToDebugStream(QDebug UNUSED stream) const {
}

}}}
