/**
 * intermediate_format/errors/CurrentCallFailReason.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): acb05780df08737af32a1979cb66a2b1db5df1f7bf979601ab8f2994edddc9eb
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/errors/CurrentCallFailReason.h"
#include "utils/qt/shortcuts.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

QString name_for_current_call_fail_reason(CurrentCallFailReason reason) {
    switch (reason) {
        case CurrentCallFailReason::UNDETERMINED:
            return "undetermined";
        case CurrentCallFailReason::CONNECTION_DROPPED:
            return "connection dropped";
    }

    invariant_violation("Invalid CurrentCallFailReason value (%d)", reason);
}

QDebug operator<< (QDebug stream, CurrentCallFailReason reason) {
    stream << QP(name_for_current_call_fail_reason(reason));

    return stream;
}

QDataStream& operator<< (QDataStream& mut_stream, CurrentCallFailReason reason) {
    mut_stream << (quint32)reason;

    return mut_stream;
}

}}}
