/**
 * intermediate_format/errors/CurrentCallFailReason.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): a7a860bc51eb3c50d20f1b12af4d3e15550668822b54b9c940ff6974f02d22b8
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/errors/CurrentCallFailReason.h"
#include "utils/qt/shortcuts.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

QString name_for_current_call_fail_reason(CurrentCallFailReason reason) {
    switch (reason) {
        case CurrentCallFailReason::UNDETERMINED:
            return "undetermined";
        case CurrentCallFailReason::CONNECTION_DROPPED:
            return "connection dropped";
    }

    invariant_violation("Invalid CurrentCallFailReason value (%d)", reason);
}

QDebug operator<< (QDebug stream, CurrentCallFailReason reason) {
    stream << QP(name_for_current_call_fail_reason(reason));

    return stream;
}

}}}
