/**
 * intermediate_format/errors/CurrentCallFailReason.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 3cce60ca954365dc36582f73c339cce45add0e538e12490ab6333af2a34a31cf
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/errors/CurrentCallFailReason.h"
#include "utils/qt/shortcuts.h"
#include "utils/serialization/deserialization_helpers.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

using namespace uniarchive2::utils::serialization;

QString name_for_current_call_fail_reason(CurrentCallFailReason reason) {
    switch (reason) {
        case CurrentCallFailReason::UNDETERMINED:
            return "undetermined";
        case CurrentCallFailReason::CONNECTION_DROPPED:
            return "connection dropped";
    }

    invariant_violation("Invalid CurrentCallFailReason value (%lld)", (int64_t)reason);
}

QDebug operator<< (QDebug stream, CurrentCallFailReason reason) {
    stream << QP(name_for_current_call_fail_reason(reason));

    return stream;
}

QDataStream& operator>> (QDataStream& mut_stream, CurrentCallFailReason& mut_reason) {
    uint8_t code = must_deserialize(mut_stream, uint8_t);

    switch ((CurrentCallFailReason)code) {
        case CurrentCallFailReason::UNDETERMINED:
        case CurrentCallFailReason::CONNECTION_DROPPED:
            mut_reason = (CurrentCallFailReason)code;
            break;
        default:
            invariant_violation("Invalid deserialized CurrentCallFailReason value (%lld)", (int64_t)code);
    }

    return mut_stream;
}

QDataStream& operator<< (QDataStream& mut_stream, CurrentCallFailReason reason) {
    mut_stream << (uint8_t)reason;

    return mut_stream;
}

}}}
