/**
 * intermediate_format/errors/MediaError.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): fd91686228e92b9d2c50601d7473e4a323b5538c68af847351ad14f2e69bd9dc
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/errors/MediaError.h"
#include "utils/qt/shortcuts.h"
#include "utils/serialization/deserialization_helpers.h"

#include <QMap>
#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

using namespace uniarchive2::utils::serialization;

QString name_for_media_error(MediaError error) {
    switch (error) {
        case MediaError::UNDETERMINED:
            return "undetermined";
        case MediaError::OMITTED:
            return "omitted";
    }

    invariant_violation("Invalid MediaError value (%lld)", (int64_t)error);
}

QString symbol_for_media_error(MediaError error) {
    switch (error) {
        case MediaError::UNDETERMINED:
            return "undetermined";
        case MediaError::OMITTED:
            return "omitted";
    }

    invariant_violation("Invalid MediaError value (%lld)", (int64_t)error);
}

MediaError media_error_from_symbol(IMM(QString) symbol) {
    const static QMap<QString, MediaError> MAP = {
        { "undetermined", MediaError::UNDETERMINED },
        { "omitted",      MediaError::OMITTED },
    };

    if (MAP.contains(symbol)) {
        return MAP[symbol];
    }

    invariant_violation("Invalid MediaError symbol ('%s')", QP(symbol));
}

QDebug operator<< (QDebug stream, MediaError error) {
    stream << QP(name_for_media_error(error));

    return stream;
}

QDataStream& operator>> (QDataStream& mut_stream, MediaError& mut_error) {
    uint8_t code = must_deserialize(mut_stream, uint8_t);

    switch ((MediaError)code) {
        case MediaError::UNDETERMINED:
        case MediaError::OMITTED:
            mut_error = (MediaError)code;
            break;
        default:
            invariant_violation("Invalid deserialized MediaError value (%lld)", (int64_t)code);
    }

    return mut_stream;
}

QDataStream& operator<< (QDataStream& mut_stream, MediaError error) {
    mut_stream << (uint8_t)error;

    return mut_stream;
}

}}}
