/**
 * intermediate_format/errors/OfferWebcamFailReason.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): bd94f688ea458b7c19fd374397a204b18dea57c1b7ae6f24e8b5ac912ac56e3a
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/errors/OfferWebcamFailReason.h"
#include "utils/qt/shortcuts.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

QString name_for_offer_webcam_fail_reason(OfferWebcamFailReason reason) {
    switch (reason) {
        case OfferWebcamFailReason::UNDETERMINED:
            return "undetermined";
        case OfferWebcamFailReason::UNSUPPORTED:
            return "unsupported";
    }

    invariant_violation("Invalid OfferWebcamFailReason value (%d)", reason);
}

QDebug operator<< (QDebug stream, OfferWebcamFailReason reason) {
    stream << QP(name_for_offer_webcam_fail_reason(reason));

    return stream;
}

QDataStream& operator<< (QDataStream& mut_stream, OfferWebcamFailReason reason) {
    mut_stream << (uint32_t)reason;

    return mut_stream;
}

}}}
