/**
 * intermediate_format/errors/OfferWebcamFailReason.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 5ad8a1b451fc92af6087639850bdc30c7581faf6c4fd0f9c46903cb88514f1f6
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_OFFERWEBCAMFAILREASON_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_OFFERWEBCAMFAILREASON_H

#include <QString>
#include <QDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

enum class OfferWebcamFailReason {
    UNDETERMINED = 0,
    UNSUPPORTED,
};

QString name_for_offer_webcam_fail_reason(OfferWebcamFailReason reason);

QDebug operator<< (QDebug stream, OfferWebcamFailReason reason);

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_OFFERWEBCAMFAILREASON_H
