/**
 * intermediate_format/errors/OfferWebcamFailReason.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): bd9fff753edd23ba72d1e4b7b49d5590d5691f432191176425e77c93144c1890
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_OFFERWEBCAMFAILREASON_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_OFFERWEBCAMFAILREASON_H

#include "utils/language/shortcuts.h"

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

enum class OfferWebcamFailReason : uint8_t {
    UNDETERMINED = 0,
    UNSUPPORTED,
};

QString name_for_offer_webcam_fail_reason(OfferWebcamFailReason reason);

QString symbol_for_offer_webcam_fail_reason(OfferWebcamFailReason reason);
OfferWebcamFailReason offer_webcam_fail_reason_from_symbol(IMM(QString) symbol);

QDebug operator<< (QDebug stream, OfferWebcamFailReason reason);

QDataStream& operator>> (QDataStream& mut_stream, OfferWebcamFailReason& mut_reason);
QDataStream& operator<< (QDataStream& mut_stream, OfferWebcamFailReason reason);

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_OFFERWEBCAMFAILREASON_H
