/**
 * intermediate_format/errors/PingFailReason.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): bdd656fb84d4ec3e7a9dfaeaec992ef7945b20a3bc8e0f2e7e7727e4212c2b7b
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_PINGFAILREASON_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_PINGFAILREASON_H

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

enum class PingFailReason {
    UNDETERMINED = 0,
    BLOCKED_OR_UNSUPPORTED,
};

QString name_for_ping_fail_reason(PingFailReason reason);

QDebug operator<< (QDebug stream, PingFailReason reason);
QDataStream& operator<< (QDataStream& mut_stream, PingFailReason reason);

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_PINGFAILREASON_H
