/**
 * intermediate_format/errors/PingFailReason.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): a49834c15f7b99ca53836f2cad7a523f231bcc844dfee17ad1e8079e9feb2ee8
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/errors/PingFailReason.h"
#include "utils/qt/shortcuts.h"
#include "utils/serialization/deserialization_helpers.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

using namespace uniarchive2::utils::serialization;

QString name_for_ping_fail_reason(PingFailReason reason) {
    switch (reason) {
        case PingFailReason::UNDETERMINED:
            return "undetermined";
        case PingFailReason::BLOCKED_OR_UNSUPPORTED:
            return "blocked or unsupported";
    }

    invariant_violation("Invalid PingFailReason value (%lld)", (int64_t)reason);
}

QDebug operator<< (QDebug stream, PingFailReason reason) {
    stream << QP(name_for_ping_fail_reason(reason));

    return stream;
}

QDataStream& operator>> (QDataStream& mut_stream, PingFailReason& mut_reason) {
    uint8_t code = must_deserialize(mut_stream, uint8_t);

    switch ((PingFailReason)code) {
        case PingFailReason::UNDETERMINED:
        case PingFailReason::BLOCKED_OR_UNSUPPORTED:
            mut_reason = (PingFailReason)code;
            break;
        default:
            invariant_violation("Invalid deserialized PingFailReason value (%lld)", (int64_t)code);
    }

    return mut_stream;
}

QDataStream& operator<< (QDataStream& mut_stream, PingFailReason reason) {
    mut_stream << (uint8_t)reason;

    return mut_stream;
}

}}}
