/**
 * intermediate_format/errors/SendMessageFailReason.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): 4d594e75a9c18aa67aaaa7bf3ab4df2f96b5ca7c36325acd2662815db94545ee
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_SENDMESSAGEFAILREASON_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_SENDMESSAGEFAILREASON_H

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

enum class SendMessageFailReason : uint8_t {
    UNDETERMINED = 0,
    MESSAGE_TOO_LARGE,
    RECIPIENT_OFFLINE,
    CONNECTION_ERROR,
};

QString name_for_send_message_fail_reason(SendMessageFailReason reason);

QDebug operator<< (QDebug stream, SendMessageFailReason reason);
QDataStream& operator<< (QDataStream& mut_stream, SendMessageFailReason reason);

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_SENDMESSAGEFAILREASON_H
