/**
 * intermediate_format/errors/SendMessageFailReason.h
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): dcd06d5c5e885e09d4873841389f791634a3d2b03d55140b1f309444fc12f290
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#ifndef UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_SENDMESSAGEFAILREASON_H
#define UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_SENDMESSAGEFAILREASON_H

#include "utils/language/shortcuts.h"

#include <QDataStream>
#include <QDebug>
#include <QString>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

enum class SendMessageFailReason : uint8_t {
    UNDETERMINED = 0,
    MESSAGE_TOO_LARGE,
    RECIPIENT_OFFLINE,
    CONNECTION_ERROR,
};

QString name_for_send_message_fail_reason(SendMessageFailReason reason);

QString symbol_for_send_message_fail_reason(SendMessageFailReason reason);
SendMessageFailReason send_message_fail_reason_from_symbol(IMM(QString) symbol);

QDebug operator<< (QDebug stream, SendMessageFailReason reason);

QDataStream& operator>> (QDataStream& mut_stream, SendMessageFailReason& mut_reason);
QDataStream& operator<< (QDataStream& mut_stream, SendMessageFailReason reason);

}}}

#endif //UNIARCHIVE2_INTERMEDIATE_FORMAT_ERRORS_SENDMESSAGEFAILREASON_H
