/**
 * intermediate_format/errors/SendMessageFailReason.cpp
 *
 * WARNING: This file is autogenerated. To make changes, edit autogen_config.yml instead and re-generate.
 * Codegen hash (sha256): d8312b7b244faba3e5aa32da488663ffd5ab472c07dd977cf5a902958bcc8765
 *
 * (C) Copyright 2014-present  Cristian Dinu <goc9000@gmail.com>
 *
 * This file is part of UniArchive II.
 *
 * Licensed under the GPL-3
 */

#include "intermediate_format/errors/SendMessageFailReason.h"
#include "utils/qt/shortcuts.h"
#include "utils/serialization/deserialization_helpers.h"

#include <QtDebug>

namespace uniarchive2 { namespace intermediate_format { namespace errors {

using namespace uniarchive2::utils::serialization;

QString name_for_send_message_fail_reason(SendMessageFailReason reason) {
    switch (reason) {
        case SendMessageFailReason::UNDETERMINED:
            return "undetermined";
        case SendMessageFailReason::MESSAGE_TOO_LARGE:
            return "message too large";
        case SendMessageFailReason::RECIPIENT_OFFLINE:
            return "recipient offline";
        case SendMessageFailReason::CONNECTION_ERROR:
            return "connection error";
    }

    invariant_violation("Invalid SendMessageFailReason value (%lld)", (int64_t)reason);
}

QDebug operator<< (QDebug stream, SendMessageFailReason reason) {
    stream << QP(name_for_send_message_fail_reason(reason));

    return stream;
}

QDataStream& operator>> (QDataStream& mut_stream, SendMessageFailReason& mut_reason) {
    uint8_t code = must_deserialize(mut_stream, uint8_t);

    switch ((SendMessageFailReason)code) {
        case SendMessageFailReason::UNDETERMINED:
        case SendMessageFailReason::MESSAGE_TOO_LARGE:
        case SendMessageFailReason::RECIPIENT_OFFLINE:
        case SendMessageFailReason::CONNECTION_ERROR:
            mut_reason = (SendMessageFailReason)code;
            break;
        default:
            invariant_violation("Invalid deserialized SendMessageFailReason value (%lld)", (int64_t)code);
    }

    return mut_stream;
}

QDataStream& operator<< (QDataStream& mut_stream, SendMessageFailReason reason) {
    mut_stream << (uint8_t)reason;

    return mut_stream;
}

}}}
